## Travis-CI configuration for puredata

# build on: linux
# TODO: coverity: pushes to the 'coverity_scan' branch will run through coverity-scan

language: c
env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  # LATER: shouldn't this be set via env-variable in the webinterface for
  # travis-ci?
  - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
  - COVERITY_SCAN_NOTIFICATION_EMAIL="dev@umlaeute.mur.at"
  - COVERITY_SCAN_BUILD_COMMAND="make"
  - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"


before_install:
- sudo apt-get update -qq
- sudo apt-get build-dep puredata -qq

before_script:
  - autoreconf -fiv
  - ./configure --enable-alsa --enable-jack --disable-portaudio
  # implement Coverity Scan with before_script instead of addons.coverity_scan
  # to work around too-early quota check by the coverity_scan addon
  - if [[ "x${TRAVIS_OS_NAME}" = "DISABLEDxlinux" ]] ; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true ; fi

script:
- make


